#!/usr/bin/ruby
# Historic helper that rendered README.textile via RedCloth.
# The project README is now Markdown (../README.md); prefer viewing that on GitHub.
# This script copies the Markdown into Docs/index.html as a plain <pre> fallback.

def r(file)
  File.read(file)
end

def render
  template = r("template.html")
  docs = "<pre>#{r('../README.md')}</pre>"
  html = template.gsub("__content__", docs)
  File.open("index.html", "w") { |f| f.write(html) }
end

render
